# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-11 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_archive_admin_map_officer_transfer_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='transfer_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='owner',
            name='ownership',
        ),
        migrations.AddField(
            model_name='owner',
            name='ownership_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Corporate', 'Corporate')], max_length=200, null=True),
        ),
    ]
