# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-14 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210814_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_request',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.owner'),
        ),
        migrations.AlterField(
            model_name='transfer_request',
            name='land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.land'),
        ),
    ]
