# Generated by Django 3.2.6 on 2021-08-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20210817_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land',
            name='name',
        ),
    ]
