# Generated by Django 3.2.6 on 2021-08-23 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20210823_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='land',
        ),
        migrations.AddField(
            model_name='owner',
            name='poly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.poly'),
        ),
        migrations.AlterField(
            model_name='poly',
            name='zip_code',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
