# Generated by Django 3.2.6 on 2021-08-23 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20210823_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer_request',
            name='land',
        ),
        migrations.AddField(
            model_name='transfer_request',
            name='poly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.poly'),
        ),
    ]
