# Generated by Django 3.2.6 on 2021-08-23 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_transfer_request_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_request',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.owner'),
        ),
    ]
