# Generated by Django 3.2.6 on 2021-08-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_remove_owner_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='poly',
        ),
        migrations.AddField(
            model_name='poly',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.owner'),
        ),
    ]
