# Generated by Django 3.2.6 on 2021-08-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20210828_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer_request',
            name='owner',
        ),
        migrations.AddField(
            model_name='transfer_request',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciever', to='accounts.owner'),
        ),
        migrations.AddField(
            model_name='transfer_request',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='accounts.owner'),
        ),
    ]
