# Generated by Django 3.2.6 on 2021-08-29 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20210828_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poly',
            old_name='polyg',
            new_name='geom',
        ),
        migrations.AlterField(
            model_name='poly',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.owner'),
        ),
    ]
