# Generated by Django 3.2.6 on 2021-09-01 08:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20210829_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poly',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='poly',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, null=True, srid=4326),
        ),
    ]
