# Generated by Django 3.2.6 on 2021-09-01 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20210901_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='grant_land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poly1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.poly')),
                ('reciever1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciever1', to='accounts.owner')),
            ],
        ),
    ]
