# Generated by Django 3.2.6 on 2021-09-02 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_grant_land'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant_land',
            old_name='poly1',
            new_name='grant_poly',
        ),
        migrations.RemoveField(
            model_name='grant_land',
            name='reciever1',
        ),
        migrations.AddField(
            model_name='grant_land',
            name='grant_reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_reciever', to='accounts.owner'),
        ),
    ]
